INSERT INTO tb_categorias (nome, criado) values ('teste', NOW());
INSERT INTO tb_categorias (nome, criado) values ('teste1', NOW());
INSERT INTO tb_categorias (nome, criado) values ('teste2', NOW());
INSERT INTO tb_categorias (nome, criado) values ('teste3', NOW());
INSERT INTO tb_categorias (nome, criado) values ('teste4', NOW());

INSERT INTO tb_produtos (nome, descricao, preco, criado) VALUES ('The Lord of the Rings', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 90.5, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('Smart TV',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',  2190.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('Macbook Pro',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1250.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1200.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('Rails for Dummies',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 100.99, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Ex',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1350.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer X',   'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1350.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Alfa',   'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1850.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Tera',   'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1950.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Y',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1700.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Nitro',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1450.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Card',   'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1850.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Plus',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1350.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');
INSERT INTO tb_produtos  (nome, descricao, preco, criado) VALUES ('PC Gamer Hera',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 2250.0, TIMESTAMP WITH TIME ZONE '2020-07-13T20:50:07.12345Z');

INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (1, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (2, 1);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (2, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (3, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (4, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (5, 2);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (6, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (7, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (8, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (9, 3);
INSERT INTO tb_produto_categoria (produto_id, categoria_id) VALUES (10, 3);

INSERT INTO tb_roles (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_roles (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_roles (authority) VALUES ('ROLE_CLIENT');
